### ISSUE TITLE
PHP Fatal error:  Uncaught ErrorException: unlink

### ISSUE THREAD

**Issue by gadangmadhulika** [Studio-42/elFinder#3134] opened 2020-03-26 10:31 UTC
Hi @nao-pon

I updated the following for Multifile .zip to work but iam facing the Php Fatal error i mentioned below.Please help me to fix the error exception occurring in the console. 
1. Composer update barryvdh/laravel-elfinder (0.4.0)
2.Composer update studio-42/elfinder (2.1.55)

PHP Fatal error:  Uncaught ErrorException: unlink(C:\Users\user\Documents\project\vendor\studio-42\elfinder\php\.tmp\zdlD99.tmp): Resource temporarily unavailable in C:\Users\user\Documents\project\vendor\studio-42\elfinder\php\elFinder
.class.php:5207
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'unlink(C:\\Users...', 'C:\\Users\\user\\...', 5207, Array)
#1 C:\Users\user\Documents\project\vendor\studio-42\elfinder\php\elFinder.class.php(5207): unlink('C:\\Users\\user\\...')
#2 [internal function]: elFinder::onShutdown()
#3 {main}
  thrown in C:\Users\user\Documents\project\vendor\studio-42\elfinder\php\elFinder.class.php on line 5207

**Comment by nao-pon** [comment] 2020-03-26 14:58
@gadangmadhulika This is a guess. Perhaps it is trying to open a temporary file created by the script and delete it without closing it. I try to modify the opened file to explicitly close when finished.

**Comment by gadangmadhulika** [comment] 2020-03-27 04:59
Hi @nao-pon 
After studio-42/elfinder update, i can see files directory in file manager but i dont want files directory to be shown.I need only Root directory to be shown.How can i remove files directory from file manager?
Please follow the below screencast
https://www.screencast.com/t/dqWZSDjRt7qh

**Comment by nao-pon** [comment] 2020-03-27 06:20
@gadangmadhulika Please make another issue because that is not related to the subject of this issue. And you should first read the Wiki connector settings and post anything you do not understand.

**Comment by gadangmadhulika** [comment] 2020-03-27 06:32
@nao-pon sure.

**Comment by gadangmadhulika** [comment] 2020-03-27 06:37
> @gadangmadhulika This is a guess. Perhaps it is trying to open a temporary file created by the script and delete it without closing it. I try to modify the opened file to explicitly close when finished.
@nao-pon Thank you for your response.

**Closed** 2020-03-28 08:36 UTC
Labels: connector bug

**Comment by nao-pon** [comment] 2020-03-28 08:38
@gadangmadhulika I fixed this, but it may not be correct because my environment does not reproduce this problem. so if you still have problems, you can reopen this issue.

**Comment by gadangmadhulika** [comment] 2020-03-28 15:46
Hi @nao-pon 
Iam getting the issue(php fatal error) in the console when i download the multiple files.

**Comment by nao-pon** [comment] 2020-03-31 04:21
@gadangmadhulika Does it mean that nothing changes when you verify it with a nightly build?
