### ISSUE TITLE
FTP files and folder with time

### ISSUE THREAD

**Issue by wlady-cs** [Studio-42/elFinder#2960] opened 2019-07-12 14:53 UTC
Hello,

I've a strange issue. I use FTP driver, but all files and folders have time before name (for ex. 12:35 FOLDER), and I'm not able to enter any folder

Can anyone help me?

thanks

**Comment by nao-pon** [comment] 2019-07-26 11:46
@wlady-cs It seems that parsing of the raw data returned by the FTP server has failed. Provide the app name of your FTP server and the format of the raw result data of the `ftp_rawlist()` command.

**Comment by nao-pon** [comment] 2019-11-30 02:47
Close this because I can't reproduce this problem. You can reopen with detailed information.

**Closed by nao-pon** 2019-11-30 02:47 UTC
