### ISSUE TITLE
HOW TO MOUNT SPECIFIC FOLDER INSIDE ONEDRIVE USING ELFINDER NETMOUNT

### ISSUE THREAD

**Issue by RAMKUMARIITR** [Studio-42/elFinder#3173] opened 2020-06-03 12:08 UTC
@nao-pon 
my root array >>
```
$opts['roots'][] = array_merge($tmbConfig, array(
    'id'       => '1', // set parent to Volume group (g1_) root "/" (Lw)
    'driver'      => 'OneDrive',
    'path'        => '/', // or folder id as root 
    'accessToken' => json_encode($ac_trail),  // @JSON String access token including refresh token
));
```

when I type folder name inside "path" error is popping up

what is folder id? is that something different than folder name or where can i get that folder id

**Comment by nao-pon** [comment] 2020-06-05 13:04
@RAMKUMARIITR It can be obtained from the network mount dialog. You can also find it on the OneDrive website.
![200605-214053](https://user-images.githubusercontent.com/1412630/83879337-72134100-a778-11ea-9a1e-a6da594ed6f1.png)

**Comment by RAMKUMARIITR** [comment] 2020-06-05 15:18
> @RAMKUMARIITR It can be obtained from the network mount dialog. You can also find it on the OneDrive website.
> ![200605-214053](https://user-images.githubusercontent.com/1412630/83879337-72134100-a778-11ea-9a1e-a6da594ed6f1.png)

Thank you... It worked.

**Comment by RAMKUMARIITR** [comment] 2020-06-07 23:33
@nao-pon Mounting of specific folder is successful only if that folder is mounted at least once before. directly by entering folder id in path variable no mounting happening [loading bar slowly moves till 75% and stop]

**Comment by RAMKUMARIITR** [comment] 2020-06-07 23:41
@nao-pon Mounting of a specific folder is successful only if that folder is mounted at least once before. directly by entering folder id in path variable no mounting happening [loading bar slowly moves till 75% and stop]


one thing which we explored was : 
The data of a previously mounted specific folder is being stored in cookies
When we change folder id and clear browser cookies then it is working 
But when we change folder id without clearing browser cookies elfinder hangs a loading bar 80%.

**Comment by nao-pon** [comment] 2020-11-30 12:29
@RAMKUMARIITR I have been away for a long time... 

When I opened OneDrive for the first time in a while, it was not operating normally. The cause was that ca-bundle.crt was out of date and the PHP open_basedir setting was enabled.

I made a fix to the open_basedir setting on the OneDrive connector and updated ca-bundle.crt and it works fine in my environment.

Thanks!

**Comment by nao-pon** [comment] 2021-06-09 14:16
Issue only accepts bug report and document request, so I'll close it.

Others can be posted to [Discussions](https://github.com/Studio-42/elFinder/discussions). [Please post to Discussions](https://github.com/Studio-42/elFinder/discussions/new) if necessary.

**Closed by nao-pon** 2021-06-09 14:16 UTC
Labels: question
