### ISSUE TITLE
Remove folder always fail

### ISSUE THREAD

**Issue by weiluo8791** [Studio-42/elFinder#2791] opened 2018-12-06 20:44 UTC
I think there is a problem within elFinderVolumeDriver.class.php in the localRmdirRecursive function. It will always return false when delete a folder. Reason being when it call the first piece of code (WIN) to remove a folder with 'rd /S /Q' this will actually remove all sub file/folder and the parent (the folder being deleted in $dir) so when it get to the next piece of del /F /Q $r will always equal 1 because the folder is already deleted. Then it flow down to unlink which will always return false as well. 

```php
protected static function localRmdirRecursive($dir) {
		// try system command
		if (is_callable('exec')) {
			$o = '';
			$r = 1;
			if (substr(PHP_OS, 0, 3) === 'WIN') {
				exec('rd /S /Q ' . escapeshellarg($dir), $o, $r);
				if ($r === 0) {
					exec('del /F /Q ' . escapeshellarg($dir), $o, $r);
				}
			} else {
				exec('rm -rf ' . escapeshellarg($dir), $o, $r);
			}
			if ($r === 0) {
				return true;
			}
		}
		if (!is_link($dir) && is_dir($dir)) {
			chmod($dir, 0777);
			if ($handle = opendir($dir)) {
				while (false !== ($file = readdir($handle))) {
					if ($file === '.' || $file === '..') {
						continue;
					}
					elFinder::extendTimeLimit(30);
					$path = $dir . DIRECTORY_SEPARATOR . $file;
					if (!is_link($dir) && is_dir($path)) {
						self::localRmdirRecursive($path);
					} else {
						chmod($path, 0666);
						unlink($path);
					}
				}
				closedir($handle);
			}
			return rmdir($dir);
		} else {
			chmod($dir, 0666);
			return unlink($dir);
		}
		return false;
	}
```

**Comment by nao-pon** [comment] 2018-12-07 11:48
@weiluo8791 This seems to be caused by the following part.

```php
				exec('rd /S /Q ' . escapeshellarg($dir), $o, $r);
				if ($r === 0) {
					exec('del /F /Q ' . escapeshellarg($dir), $o, $r);
				}
```

Perhaps it should be fixed as follows. I will fix this.

```php
				exec('rd /S /Q ' . escapeshellarg($dir), $o, $r);
				if ($r !== 0) {
					exec('del /F /Q ' . escapeshellarg($dir), $o, $r);
				}
```

Thanks! 👍

**Closed** 2018-12-07 12:12 UTC
Labels: connector bug

**Comment by weiluo8791** [comment] 2018-12-07 16:15
Thank you for the quick fix
