### ISSUE TITLE
Unable to Create Archive, Permission Denied

### ISSUE THREAD

**Issue by Swapnil511994** [Studio-42/elFinder#3115] opened 2020-02-25 05:31 UTC
I'm facing an issue while selecting and downloading multiple files
below is my connector:

```php

error_reporting(0); // Set E_ALL for debuging

elFinder::$netDrivers['ftp'] = 'FTP';

function access($attr, $path, $data, $volume, $isDir, $relpath) {
	$basename = basename($path);
	return $basename[0] === '.'                  // if file/folder begins with '.' (dot)
			 && strlen($relpath) !== 1           // but with out volume root
		? !($attr == 'read' || $attr == 'write') // set read+write to false, other (locked+hidden) set to true
		:  null;                                 // else elFinder decide it itself
}


// Documentation for connector options:
// https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options
$opts = array(
	// 'debug' => true,
	'roots' => array(
		// Items volume
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../../documents/',                 // path to files (REQUIRED)
'attributes' => array(
　　　　　　　　　// The first matching of the multiple patterns will be applied. (elFinder >= 2.1.33)
		array(
			// You can also set permissions for file types by adding, for example, \.jpg inside pattern.
                        // The path for pattern evaluation is passed by converting the path as the root to '/'.
                        'pattern' => '/^\/TEST$/',
			'read'    => true,
			'write'   => true,
			'locked'  => false,
		)
	),
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image/x-ms-bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/x-icon', 'text/plain'), // Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		),
		array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../../videos/',                 // path to files (REQUIRED)
'attributes' => array(
　　　　　　　　　// The first matching of the multiple patterns will be applied. (elFinder >= 2.1.33)
		array(
			// You can also set permissions for file types by adding, for example, \.jpg inside pattern.
                        // The path for pattern evaluation is passed by converting the path as the root to '/'.
                        'pattern' => '/^\/TEST$/',
			'read'    => true,
			'write'   => true,
			'locked'  => false
		)
	),
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image/x-ms-bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/x-icon', 'text/plain'), // Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		),
array(
			'driver'        => 'LocalFileSystem',           // driver for accessing file system (REQUIRED)
			'path'          => '../../photograph/',                 // path to files (REQUIRED)
'attributes' => array(
　　　　　　　　　// The first matching of the multiple patterns will be applied. (elFinder >= 2.1.33)
		array(
			// You can also set permissions for file types by adding, for example, \.jpg inside pattern.
                        // The path for pattern evaluation is passed by converting the path as the root to '/'.
                        'pattern' => '/^\/TEST$/',
			'read'    => true,
			'write'   => true,
			'locked'  => true,
		)
	),
			'URL'           => dirname($_SERVER['PHP_SELF']) . '/../files/', // URL to files (REQUIRED)
			'trashHash'     => 't1_Lw',                     // elFinder's hash of trash folder
			'winHashFix'    => DIRECTORY_SEPARATOR !== '/', // to make hash same to Linux one on windows too
			'uploadDeny'    => array('all'),                // All Mimetypes not allowed to upload
			'uploadAllow'   => array('image/x-ms-bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/x-icon', 'text/plain'), // Mimetype `image` and `text/plain` allowed to upload
			'uploadOrder'   => array('deny', 'allow'),      // allowed Mimetype `image` and `text/plain` only
			'accessControl' => 'access'                     // disable and hide dot starting files (OPTIONAL)
		),

			)
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();


```

**Comment by Swapnil511994** [comment] 2020-02-25 05:33
I'm using digital Ocean, this was successfully running on godaddy VPS

**Comment by nao-pon** [comment] 2020-02-25 11:15
@Swapnil511994 Check that "php/.tmp" exists and that PHP has write permission.

**Comment by Swapnil511994** [comment] 2020-02-25 12:10
Hi @nao-pon the ".tmp" exists in php folder and has writable permission

**Comment by nao-pon** [comment] 2020-02-25 12:20
@Swapnil511994 If so, PHP can't use the zip or gzip commands on your server, and can't use PHP's ZipArchive class. At least one of them must be available. Please ask your server administrator.

**Comment by Swapnil511994** [comment] 2020-02-25 12:26
Hi @nao-pon thanks for replying,
I have php-zip installed on server 
root@isdat:~# sudo apt install php-zip
Reading package lists... Done
Building dependency tree
Reading state information... Done
php-zip is already the newest version (2:7.4+73+ubuntu16.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
root@isdat:~#

**Comment by nao-pon** [comment] 2020-02-25 14:11
@Swapnil511994 Install the following PHP script on the server and access it with a browser to observe the result.

```php
<?php
exec('gzip --version', $o_gzip, $r_gzip);
exec('zip -h', $o_zip, $r_zip);
$phpzip = class_exists('ZipArchive', false);

header('Content-Type: text/plain');
var_dump(array(
	'gzip' => array($o_gzip, $r_gzip),
	'zip' => array($o_zip, $r_zip),
	'phpzip' => $phpzip? 'Yes' : 'No'
));
```

**Comment by Swapnil511994** [comment] 2020-02-25 15:44
array(3) {
  ["gzip"]=>
  array(2) {
    [0]=>
    array(8) {
      [0]=>
      string(8) "gzip 1.6"
      [1]=>
      string(61) "Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc."
      [2]=>
      string(36) "Copyright (C) 1993 Jean-loup Gailly."
      [3]=>
      string(76) "This is free software.  You may redistribute copies of it under the terms of"
      [4]=>
      string(70) "the GNU General Public License <http://www.gnu.org/licenses/gpl.html>."
      [5]=>
      string(53) "There is NO WARRANTY, to the extent permitted by law."
      [6]=>
      string(0) ""
      [7]=>
      string(28) "Written by Jean-loup Gailly."
    }
    [1]=>
    int(0)
  }
  ["zip"]=>
  array(2) {
    [0]=>
    array(22) {
      [0]=>
      string(72) "Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license."
      [1]=>
      string(31) "Zip 3.0 (July 5th 2008). Usage:"
      [2]=>
      string(78) "zip [-options] [-b path] [-t mmddyyyy] [-n suffixes] [zipfile list] [-xi list]"
      [3]=>
      string(74) "  The default action is to add or replace zipfile entries from list, which"
      [4]=>
      string(60) "  can include the special name - to compress standard input."
      [5]=>
      string(66) "  If zipfile and list are omitted, zip compresses stdin to stdout."
      [6]=>
      string(74) "  -f   freshen: only changed files  -u   update: only changed or new files"
      [7]=>
      string(76) "  -d   delete entries in zipfile    -m   move into zipfile (delete OS files)"
      [8]=>
      string(76) "  -r   recurse into directories     -j   junk (don't record) directory names"
      [9]=>
      string(78) "  -0   store only                   -l   convert LF to CR LF (-ll CR LF to LF)"
      [10]=>
      string(56) "  -1   compress faster              -9   compress better"
      [11]=>
      string(77) "  -q   quiet operation              -v   verbose operation/print version info"
      [12]=>
      string(60) "  -c   add one-line comments        -z   add zipfile comment"
      [13]=>
      string(76) "  -@   read names from stdin        -o   make zipfile as old as latest entry"
      [14]=>
      string(73) "  -x   exclude the following names  -i   include only the following names"
      [15]=>
      string(69) "  -F   fix zipfile (-FF try harder) -D   do not add directory entries"
      [16]=>
      string(71) "  -A   adjust self-extracting exe   -J   junk zipfile prefix (unzipsfx)"
      [17]=>
      string(70) "  -T   test zipfile integrity       -X   eXclude eXtra file attributes"
      [18]=>
      string(70) "  -y   store symbolic links as the link instead of the referenced file"
      [19]=>
      string(70) "  -e   encrypt                      -n   don't compress these suffixes"
      [20]=>
      string(21) "  -h2  show more help"
      [21]=>
      string(0) ""
    }
    [1]=>
    int(0)
  }
  ["phpzip"]=>
  string(3) "Yes"
}

**Comment by nao-pon** [comment] 2020-02-26 06:57
@Swapnil511994 The result seems to be perfectly fine. Do you have the same problem after closing the browser and opening a new session?

**Comment by Swapnil511994** [comment] 2020-02-29 05:57
Yes, I've tried clearing the cache and trying in incognito mode.
Also tried using mozilla for a change

**Comment by nao-pon** [comment] 2020-03-01 09:02
@Swapnil511994 Does the connector option ["disabled"](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#disabled) include "zipdl"? I can't think of any other cause. Can you debug on source code yourself because I can't reproduce?

https://github.com/Studio-42/elFinder/blob/55a967b94ad31d46549d3297f2619dc84c3dded2/php/elFinderVolumeDriver.class.php#L2677-L2744

**Comment by Swapnil511994** [comment] 2020-03-03 09:41
Sure, I'll let you know

**Closed** 2020-03-31 04:27 UTC
Labels: question
